language: objective-c
osx_image: xcode10.2

branches:
    only:
        - develop
        - master

    before_install:
        - gem update --system
        - gem install bundler

script: fastlane ci