# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:swift)

platform :swift do
    before_all do
        setup_travis
        bundle_install
        spm(command: "update")
    end

    desc "Lints the code, autocorrecting any mistakes."
    lane :lint do
        swiftlint(mode: :autocorrect, config_file: "./.swiftlint.yml")
        swiftlint(mode: :lint, config_file: "./.swiftlint.yml")
    end

    desc "Run tests and measure code coverage"
    lane :test do
        spm(command: "generate-xcodeproj")
        scan(scheme: "Robinhood-Package", code_coverage: true)
        xcov(
            scheme: "Robinhood-Package",
            output_directory:"./fastlane/output/xcov_output",
            minimum_coverage_percentage: 90.00,
            ignore_file_path: "./fastlane/.xcovignore"
        )
        
    end

    desc "Run all checks for code quality"
    lane :verify do
        lint
        test
    end

    desc "Run all checks for CI"
    lane :ci do
        test
        danger(
            danger_id: "ci",
            dangerfile: "./Dangerfile",
            github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
            use_bundle_exec: true
        )
    end
end
